### ISSUE TITLE
Plugin leaves compiled .js files in my project

### ISSUE THREAD

**Issue by crummy** [ArnaudBarre/vite-plugin-tsc-watch#1]
I'm not totally sure what triggers it, but after a few minutes running with `    plugins: [react(), tscPlugin()]`, I end up with `src/foo/foo.js` next to my `src/foo/foo.tsx` files. This seems to trip up the vite dev build which starts resolving `src/foo` in imports to the JS file instead of the TSX.

**Comment by ArnaudBarre** [comment]
You're missing "noEmit" in your TS config I think (which is expected for Vite because SWC or esbuild are used for transpilling)

**Comment by crummy** [comment]
Thanks - that did the trick!
